### ISSUE TITLE
Database Helper 2 in SpMain

### ISSUE THREAD

**Issue by ThisisEdgar** [ThisisEdgar/ProjectMobileApp#5]
I'm trying to launch the app to test it but there is an error in SPMain, please give it a look. It is in the main brach, so if you already solved it, please let me know

**Comment by fignaciotc** [comment]
DataBaseHelper2 was deleted in the last version, now it only has dataBaseHelper

**Comment by ThisisEdgar** [comment]
Hello everyone, I would really appreciate if you could merge the changes of SPMain to the master branch, I would like to test my part of the app
